//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "event_category")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub handle: String,
    pub name: String,
    pub banner_img_url: Option<String>,
    pub hex_color: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::event_categories::Entity")]
    EventCategories,
    #[sea_orm(has_many = "super::event_edition_categories::Entity")]
    EventEditionCategories,
}

impl Related<super::event_categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventCategories.def()
    }
}

impl Related<super::event_edition_categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventEditionCategories.def()
    }
}

impl Related<super::event::Entity> for Entity {
    fn to() -> RelationDef {
        super::event_categories::Relation::Event.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::event_categories::Relation::EventCategory.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
