//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "maps")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    #[sea_orm(unique)]
    pub game_id: String,
    pub player_id: u32,
    pub name: String,
    pub cps_number: Option<u32>,
    pub linked_map: Option<u32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::LinkedMap",
        to = "Column::Id",
        on_update = "Restrict",
        on_delete = "SetNull"
    )]
    SelfRef,
    #[sea_orm(has_many = "super::player_rating::Entity")]
    PlayerRating,
    #[sea_orm(
        belongs_to = "super::players::Entity",
        from = "Column::PlayerId",
        to = "super::players::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Players,
    #[sea_orm(has_many = "super::rating::Entity")]
    Rating,
    #[sea_orm(has_many = "super::records::Entity")]
    Records,
}

impl Related<super::player_rating::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlayerRating.def()
    }
}

impl Related<super::rating::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Rating.def()
    }
}

impl Related<super::records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Records.def()
    }
}

impl Related<super::players::Entity> for Entity {
    fn to() -> RelationDef {
        super::rating::Relation::Players.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::rating::Relation::Maps.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
