//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "rating_kind")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: u8,
    pub kind: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::player_rating::Entity")]
    PlayerRating,
}

impl Related<super::player_rating::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlayerRating.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
