[package]
name = "mx-layer"
version = "0.1.0"
edition = "2024"

[dependencies]
futures.workspace = true
records-lib = { path = "../records_lib" }
reqwest.workspace = true
serde.workspace = true
tokio = { workspace = true, features = ["rt", "sync", "time"] }

[build-dependencies]
serde_json.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "sync", "time", "macros", "test-util"] }
anyhow = { workspace = true }
rand.workspace = true
