//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub mod prelude;

pub mod api_status;
pub mod api_status_history;
pub mod article;
pub mod article_authors;
pub mod banishments;
pub mod checkpoint_times;
pub mod event;
pub mod event_admins;
pub mod event_categories;
pub mod event_category;
pub mod event_edition;
pub mod event_edition_admins;
pub mod event_edition_categories;
pub mod event_edition_maps;
pub mod event_edition_records;
pub mod latestnews_image;
pub mod maps;
pub mod player_rating;
pub mod players;
pub mod players_ips;
pub mod rating;
pub mod rating_kind;
pub mod records;
pub mod resources_content;
pub mod role;
