//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "event_edition_maps")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub event_id: u32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub edition_id: u32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub map_id: u32,
    pub category_id: Option<u32>,
    pub mx_id: Option<i64>,
    pub order: u32,
    pub original_map_id: Option<u32>,
    pub original_mx_id: Option<i64>,
    pub transitive_save: Option<i8>,
    pub bronze_time: Option<i32>,
    pub silver_time: Option<i32>,
    pub gold_time: Option<i32>,
    pub author_time: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::event_edition::Entity",
        from = "(Column::EventId, Column::EditionId)",
        to = "(super::event_edition::Column::EventId, super::event_edition::Column::Id)",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    EventEdition,
    #[sea_orm(
        belongs_to = "super::event_edition_categories::Entity",
        from = "(Column::EventId, Column::EditionId, Column::CategoryId)",
        to = "(super::event_edition_categories::Column::EventId, super::event_edition_categories::Column::EditionId, super::event_edition_categories::Column::CategoryId)",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    EventEditionCategories,
    #[sea_orm(
        belongs_to = "super::maps::Entity",
        from = "Column::MapId",
        to = "super::maps::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    Maps,
    #[sea_orm(
        belongs_to = "super::maps::Entity",
        from = "Column::OriginalMapId",
        to = "super::maps::Column::Id",
        on_update = "Restrict",
        on_delete = "SetNull"
    )]
    OriginalMaps,
}

impl Related<super::event_edition::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventEdition.def()
    }
}

impl Related<super::event_edition_categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventEditionCategories.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
