//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

use crate::types::InGameAlignment;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "in_game_event_edition_params")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub put_subtitle_on_newline: Option<i8>,
    pub titles_align: Option<InGameAlignment>,
    pub lb_link_align: Option<InGameAlignment>,
    pub authors_align: Option<InGameAlignment>,
    #[sea_orm(column_type = "Double", nullable)]
    pub titles_pos_x: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub titles_pos_y: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub lb_link_pos_x: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub lb_link_pos_y: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub authors_pos_x: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub authors_pos_y: Option<f64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::event_edition::Entity")]
    EventEdition,
}

impl Related<super::event_edition::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventEdition.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
