//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "map_periodic_ranking")]
pub struct Model {
    #[sea_orm(column_type = "Double")]
    pub score: f64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub period_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub map_id: u32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::maps::Entity",
        from = "Column::MapId",
        to = "super::maps::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    Maps,
    #[sea_orm(
        belongs_to = "super::ranking_period::Entity",
        from = "Column::PeriodId",
        to = "super::ranking_period::Column::PeriodId",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    RankingPeriod,
}

impl Related<super::maps::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Maps.def()
    }
}

impl Related<super::ranking_period::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RankingPeriod.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
