//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::map_periodic_ranking::Entity as MapPeriodicRanking;
pub use super::player_periodic_ranking::Entity as PlayerPeriodicRanking;
pub use super::ranking_period::Entity as RankingPeriod;
