//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ranking_period")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub period_id: i32,
    pub period_date: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::map_periodic_ranking::Entity")]
    MapPeriodicRanking,
    #[sea_orm(has_many = "super::player_periodic_ranking::Entity")]
    PlayerPeriodicRanking,
}

impl Related<super::map_periodic_ranking::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MapPeriodicRanking.def()
    }
}

impl Related<super::player_periodic_ranking::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlayerPeriodicRanking.def()
    }
}

impl Related<super::maps::Entity> for Entity {
    fn to() -> RelationDef {
        super::map_periodic_ranking::Relation::Maps.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::map_periodic_ranking::Relation::RankingPeriod
                .def()
                .rev(),
        )
    }
}

impl Related<super::players::Entity> for Entity {
    fn to() -> RelationDef {
        super::player_periodic_ranking::Relation::Players.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::player_periodic_ranking::Relation::RankingPeriod
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
